version: 2
updates:
  - package-ecosystem: cargo
    directory: /packages/server
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: 'actix-rt'
        versions:
          - '> 1.1.1'
      - dependency-name: uuid
        versions:
          - '> 0.7.4'
    labels:
      - ':horse: chore'
    open-pull-requests-limit: 10
    reviewers:
      - ajtorres9
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    labels:
      - ':horse: chore'
    open-pull-requests-limit: 10
    reviewers:
      - ajtorres9
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: eslint-import-resolver-typescript
        versions:
          - '> 1.1.1'
    labels:
      - ':horse: chore'
    open-pull-requests-limit: 10
    reviewers:
      - ajtorres9
    versioning-strategy: increase
