packageExtensions:
  '@stylelint/postcss-markdown@*':
    dependencies:
      postcss-html: '*'
  prettier-plugin-toml@*:
    dependencies:
      '@toml-tools/lexer': '*'
  stylelint-a11y@*:
    dependencies:
      postcss: '*'
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: '@yarnpkg/plugin-workspace-tools'
yarnPath: .yarn/releases/yarn-2.1.1.cjs
