name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  root_static_analysis:
    name: Root Static Analysis
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.19
      - name: Install Yarn
        run: npm install --global yarn@1.22
      - name: Restore Node dependencies
        id: restore-node-dependencies
        uses: actions/cache@v2.1.3
        with:
          path: node_modules
          key: node-dependencies-${{ hashFiles('yarn.lock') }}
      - name: Install Node dependencies
        if: steps.restore-node-dependencies.outputs.cache-hit != 'true'
        run: yarn install --immutable --immutable-cache
      - name: Lint files
        run: yarn lint:files
  server_static_analysis:
    name: Server Static Analysis
    runs-on: ubuntu-20.04
    env:
      CARGO_INCREMENTAL: 0
      RUSTDOCFLAGS: -C panic=abort
      RUSTFLAGS: -C codegen-units=1 -C link-dead-code -C opt-level=0 -C overflow-checks=off -C panic=abort -Z panic_abort_tests -Z profile
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.19
      - name: Install Yarn
        run: npm install --global yarn@1.22
      - name: Restore Node dependencies
        id: restore-node-dependencies
        uses: actions/cache@v2.1.3
        with:
          path: node_modules
          key: node-dependencies-${{ hashFiles('yarn.lock') }}
      - name: Install Node dependencies
        if: steps.restore-node-dependencies.outputs.cache-hit != 'true'
        run: yarn install --immutable --immutable-cache
      - name: Setup Cargo cache
        run: sudo chown -H --recursive $(id --name --user):$(id --group --name) ~/.cargo
      - name: Restore Cargo cache and artifacts
        id: restore-cargo-cache-and-artifacts
        uses: actions/cache@v2.1.3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            packages/server/target
          key: server-cargo-cache-and-artifacts-${{ hashFiles('packages/server/Cargo.lock') }}
      - name: Install Rust and Cargo
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly-2020-10-25
          default: true
          profile: minimal
          components: clippy, rustfmt
      - name: Install Rust dependencies
        run: cargo install --version 0.5.15 grcov || exit 0
      - name: Build
        if: steps.restore-cargo-cache-and-artifacts.outputs.cache-hit != 'true'
        run: yarn build
        working-directory: packages/server
      - name: Lint files, scripts, and types
        run: yarn lint
        working-directory: packages/server
      - name: Cleanup artifacts
        run: rm --force --recursive packages/server/target/{debug/{{.fingerpint,deps}/server-*,examples,incremental,.cargo-lock,server{,.d*}},.rustc_info.json}
  server_test:
    name: Server Test
    runs-on: ubuntu-20.04
    env:
      CARGO_INCREMENTAL: 0
      RUSTDOCFLAGS: -C panic=abort
      RUSTFLAGS: -C codegen-units=1 -C link-dead-code -C opt-level=0 -C overflow-checks=off -C panic=abort -Z panic_abort_tests -Z profile
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.19
      - name: Install Yarn
        run: npm install --global yarn@1.22
      - name: Restore Node dependencies
        id: restore-node-dependencies
        uses: actions/cache@v2.1.3
        with:
          path: node_modules
          key: node-dependencies-${{ hashFiles('yarn.lock') }}
      - name: Install Node dependencies
        if: steps.restore-node-dependencies.outputs.cache-hit != 'true'
        run: yarn install --immutable --immutable-cache
      - name: Setup Cargo cache
        run: sudo chown -H --recursive $(id --name --user):$(id --group --name) ~/.cargo
      - name: Restore Cargo cache and artifacts
        id: restore-cargo-cache-and-artifacts
        uses: actions/cache@v2.1.3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
            packages/server/target
          key: server-cargo-cache-and-artifacts-${{ hashFiles('packages/server/Cargo.lock') }}
      - name: Install Rust and Cargo
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly-2020-10-25
          default: true
          profile: minimal
      - name: Install Rust dependencies
        run: cargo install --version 0.5.15 grcov || exit 0
      - name: Build
        if: steps.restore-cargo-cache-and-artifacts.outputs.cache-hit != 'true'
        run: yarn build
        working-directory: packages/server
      - name: Test units
        run: yarn test:units
        working-directory: packages/server
      - name: Generate code coverage report
        run: |
          mkdir coverage
          grcov --branch --ignore '/*' --ignore-not-existing --llvm --output-path coverage/lcov.info --source-dir . target
        working-directory: packages/server
      - name: Publish code coverage report
        uses: codecov/codecov-action@v1.0.15
        with:
          file: packages/server/coverage/lcov.info
          flags: server
      - name: Cleanup artifacts
        run: rm --force --recursive packages/server/target/{debug/{{.fingerpint,deps}/server-*,examples,incremental,.cargo-lock,server{,.d*}},.rustc_info.json}
  user_static_analysis:
    name: User Static Analysis
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.19
      - name: Install Yarn
        run: npm install --global yarn@1.22
      - name: Restore Node dependencies
        id: restore-node-dependencies
        uses: actions/cache@v2.1.3
        with:
          path: node_modules
          key: node-dependencies-${{ hashFiles('yarn.lock') }}
      - name: Install Node dependencies
        if: steps.restore-node-dependencies.outputs.cache-hit != 'true'
        run: yarn install --immutable --immutable-cache
      - name: Lint files, scripts, and styles
        run: yarn lint
        working-directory: packages/user
